### ISSUE TITLE
Evaluación

### ISSUE THREAD

**Issue by erickorlando** [ArmentaBautista/EProspeccion#1]
Estimado Juan Carlos:

Tu proyecto está muy bueno, asegúrate nomas de validar correctamente los estilos de los componentes y la autorización asegúrate de que tenga un mensaje hacia el usuario, por ejemplo, cuando quise registrar una prospección no sabía que como Administrador no se podía, pero por lo demás está perfecto.

**Nota: 18.5**

![InterninJobGIF](https://github.com/user-attachments/assets/fa65606d-a3cb-4dd9-88d7-a862c47d8953)

**Comment by ArmentaBautista** [comment]
Muchas gracias por todo Inge
Muchos conceptos pude entenderlos gracia a su curso
